### ISSUE TITLE
Phar Composer package

### ISSUE THREAD

**Issue by someniatko** [infection/infection#1505] opened 2021-04-19 15:06 UTC
**Is your feature request related to a problem? Please describe.**
I would like to depend on concrete version of Infection in each project in order to have reproducible builds, without having to bother with transitive dependencies of this tool itself.

**Describe the solution you'd like**
I would like a Composer package, which would not have any dependencies (except PHP version and extensions), and will only have a Phar "binary". This would combine the best of two worlds.

**Describe alternatives you've considered**
The only solutions I have is either to depend on Infection with all its transitive dependencies in Composer, or download Phar manually.

**Comment by maks-rafalko** [comment] 2021-04-19 15:48
Thank you, closing as this is a duplicate of https://github.com/infection/infection/issues/956

**Closed by maks-rafalko** 2021-04-19 15:48 UTC
