### ISSUE TITLE
False positive when calculation is in multiple lines

### ISSUE THREAD

**Issue by rieschl** [infection/infection#366] opened 2018-06-01 20:15 UTC
| Question    | Answer
| ------------| ---------------
| Infection version | dev-master#2e24f03
| Test Framework version | PHPUnit 7.2.2
| PHP version | 7.1.17
| Platform    | Debian (also tested in WSL)
| Github Repo | https://github.com/trinet-at/infection-multiline

When a calculation spans across multiple lines and infection does a mutation on it, it reports it as false positive, e.g. the original code:
```
$result = $value
    / 100
    * 100;

return $result;
```
and mutation:
```
$result = $value
    * 100
    * 100;

return $result;
```
This results in a false positive:
```
Not covered mutants:
====================

1) /mnt/e/PhpStormProjects/infection-bug/src/Calculator.php:9    [M] Division

--- Original
+++ New
@@ @@
 {
     public function calculateInMultipleLines(float $value) : float
     {
-        $result = $value / 100 * 100;
+        $result = $value * 100 * 100;
         return $result;
     }
     public function calculateInSingleLine(float $value) : float
```

When the calculation is in a single line, it works as expected:
```
$result = $value / 100 * 100;

return $result;
```
and mutation:
```
$result = $value * 100 * 100;

return $result;
```

I've created the [test repo ](https://github.com/trinet-at/infection-multiline), it's easier to see the code than to explain it :)

**Comment by BackEndTea** [comment] 2018-06-03 09:27
This is most likely due to how coverage is calculated for php. In the same way that for a multi line array, only the first value is considered covered (except when it assigned to a class property, then the assignment is considered covered)

**Comment by sanmai** [comment] 2018-06-04 03:31
It really does not report line 9 as covered...
```xml
<coverage>
  <line nr="10">
    <covered by="TrinetTest\InfectionMultiline\CalculatorTest::testCalculateInMultipleLines"/>
    <covered by="TrinetTest\InfectionMultiline\CalculatorTest::testCalculateInMultipleLinesFloat"/>
    <covered by="TrinetTest\InfectionMultiline\CalculatorTest::testCalculateInSingleLineFloat"/>
  </line>
  <line nr="11">
  ...
```

**Comment by rieschl** [comment] 2018-06-04 06:42
But is line 9 something that can be covered? It's just `$result = $value`. If it can PHOUnit seems to treat it lie whitespace because of the 100% coverage output. Line 11 and 12, which are mutated, are covered though.
Btw. looking at your coverage report I noticed that I used the wrong method call in one of the tests. I already fixed that in the latest commit.

Does infection rely that much on the coverage? I thought it just changes (mutates) one thing, reruns the tests and checks if they fail. And the tests _do_ fail.

**Comment by sanmai** [comment] 2018-06-04 06:48
Well, it tries not to mutate things that are not covered by tests.

**Comment by sanmai** [comment] 2018-06-04 06:53
The problem is that we're not accounting that a single statement can span multiple lines. A fix would look like this:
```
for ($line = $node->getStartLine(); $line <= $node->getEndLine(); ++$line) {
    if ($this->codeCoverageData->hasTestsOnLine($this->filePath, $line)) {
        return true;
    }
}
```

Now I have an E2E test failing with this change, only need to find out if that's an actual error or not.

**Comment by rieschl** [comment] 2018-06-04 07:31
Yes of course. Just copy it. You don't need to add a specific license header :)
The tests are so simple, it's questionable if something like that can even be licensed.
But be sure to grab the latest version, there was a [mistake](https://github.com/trinet-at/infection-multiline/commit/4a79053c6c3b093c15156a32ce7691052ce6285e#diff-7704e58557f7b5bb48593ccb61954047R42) in the first commit.

**Comment by borNfreee** [comment] 2018-06-10 20:12
fixed in https://github.com/infection/infection/releases/tag/0.9.0-beta.2

**Closed by borNfreee** 2018-06-10 20:12 UTC
Labels: bug, has PR
