### ISSUE TITLE
False positive uncovered mutant with `switch(true)` and `switch(false)`

### ISSUE THREAD

**Issue by luispabon** [infection/infection#819] opened 2019-11-08 12:35 UTC
| Question    | Answer
| ------------| ---------------
| Infection version | 0.14.2
| Test Framework version | PHPUnit 8.4.3
| PHP version | 7.2.24/7.3.11/7.4.0-RC4
| Platform    | Ubuntu/docker
| Github Repo | https://github.com/luispabon/favicon-finder
| Example | https://infection-php.dev/r/emew

Infection is reporting an uncovered mutant on the repository above:

```diff
Not Covered mutants:
====================


1) /home/luis/Projects/favicon/src/Favicon.php:155    [M] TrueValue

--- Original
+++ New
@@ @@
             $links = $dom->getElementsByTagName('link');
             foreach ($links as $link) {
                 /** @var DOMNode $link */
-                switch (true) {
+                switch (false) {
                     case $link->hasAttribute('rel') && strtolower($link->getAttribute('rel')) === 'shortcut icon':
                     case $link->hasAttribute('rel') && strtolower($link->getAttribute('rel')) === 'icon':
                     case $link->hasAttribute('href') && strpos($link->getAttribute('href'), 'favicon') !== false:
```
This is however a false positive. That line is indeed covered, and the switch from true to false does break tests.

You can check by cloning, `composer -o install; make`. This runs phpunit and infection in sequence, infection recycling test results from phpunit. Letting infection generate its own reports makes no difference.

Build: https://ci.auronconsulting.co.uk/teams/main/pipelines/favicon-finder-master/jobs/analyze-master/builds/1

**Comment by maks-rafalko** [comment] 2019-11-08 19:56
Duplicate of https://github.com/infection/infection/issues/34

It boils down to how PHP works internally, please read exactly the same issue we created earlier https://github.com/infection/infection/issues/34

See Derick's explanation here https://bugs.xdebug.org/view.php?id=1479#c4450

I would say it won't be fixed on Infection side unless someone wants to do some magic to make it work (similar to how @BackEndTea [did it for array coverage](https://github.com/infection/infection/pull/655))

Closing for now, feel free to reopen, fix, and discuss farther though.

**Comment by maks-rafalko** [comment] 2019-11-08 19:59
Probably, it makes sense to not mutate `switch(false)` to `switch(true)` since we know it is always marked as `Not Covered`. What do you think @luispabon and @infection/core ?

**Comment by BackEndTea** [comment] 2019-11-08 20:03
Is the switch **never** covered? Or only when its switching over true/a constant?

If its never covered we can always skip that; otherwise only for true and false mutator

**Comment by maks-rafalko** [comment] 2019-11-08 20:08
> Is the switch **never** covered?

I only saw not covered `switch` line for `true`/`false`. Just tried with an expression, and it is covered

<img width="571" alt="Code Coverage 2" src="https://user-images.githubusercontent.com/3725595/68507285-965b7d80-027c-11ea-8a75-1f8970d2c5d9.png">

**Comment by luispabon** [comment] 2019-11-08 20:38
Happy to help, could you give me any pointers of where to look? Never got my hands dirty on infection's codebase

**Comment by BackEndTea** [comment] 2019-11-08 20:42
Probably somewhere around here:
https://github.com/infection/infection/blob/50c8197f27a07c099748438ed0d7f719b26d982b/src/Mutator/Boolean/TrueValue.php#L63

My best bet would be a check to see if the direct parent is the switch statement.

**Comment by BackEndTea** [comment] 2019-11-08 20:43
For completeness sake this should also be for the `false` mutator

**Comment by sanmai** [comment] 2019-11-09 00:29
Harder, but better, will be to tag a switch as covered if any single line inside of it is covered.

**Comment by BackEndTea** [comment] 2019-11-09 00:36
I think we only need to check the case statements for that. So wed only need to go 1 level deep.

**Comment by sanmai** [comment] 2019-11-09 00:38
Or up, unconditionally tagging an uncovered switch as covered every time we see a covered case statement.

**Closed** 2024-06-21 10:21 UTC
Labels: Bug, Help Wanted, False Positive, Good First Issue / Easy Pick, Mutator
