### ISSUE TITLE
Coverage data missing

### ISSUE THREAD

**Issue by rjscully** [infection/infection#30] opened 2017-09-04 00:51 UTC
| Question    | Answer
| ------------| ---------------
| Infection version | 0.5.2
| Test Framework version | PHPUnit 6.2.4
| PHP version | 7.0.23
| Platform    | Windows
| Github Repo | N/A

### Description
On a fresh install infection fails after processing source code files is complete, just as soon as mutation begins. This happens with Composer and PHAR installation of 0.5.2. In both cases, infection was run without options.

I'm still looking into the source of the problem but maybe someone knows the answer.

<details>
 <summary>phpunit.xml</summary>
 
 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Unit Tests">
            <directory suffix="Test.php">./tests</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
    </php>
</phpunit>
```

</details>

### Runtime
Failure occurs 1-2 seconds after infection is run. The output is the same whether Composer or PHAR installation was used (excluding the expected infection path differences in the stack trace).

Invoking with:
```
php infection.phar
```

Yields this output:
<details>
 <summary>Output with issue</summary>
Running initial test suite...

    1 [============================]  1 sec

Generate mutants...

Processing source code files: 73/73
Creating mutated files and processes:   0/434PHP Warning:  file_get_contents(C:\Users\rjscully\AppData\Local\Temp/infection/coverage-xml/index.xml): failed to open stream: No such file or directory in phar://M:/Project/infection.phar/src/TestFramework/Coverage/CodeCoverageData.php on line 147
PHP Stack trace:
PHP   1. {main}() M:\Project\infection.phar:0
PHP   2. require() M:\Project\infection.phar:10
PHP   3. Symfony\Component\Console\Application->run() phar://M:/Project/infection.phar/bin/infection:33
PHP   4. Symfony\Component\Console\Application->doRun() phar://M:/Project/infection.phar/vendor/symfony/console/Application.php:127
PHP   5. Symfony\Component\Console\Application->doRunCommand() phar://M:/Project/infection.phar/vendor/symfony/console/Application.php:220
PHP   6. Infection\Command\InfectionCommand->run() phar://M:/Project/infection.phar/vendor/symfony/console/Application.php:866
PHP   7. Infection\Command\InfectionCommand->execute() phar://M:/Project/infection.phar/vendor/symfony/console/Command/Command.php:261
PHP   8. Infection\InfectionApplication->run() phar://M:/Project/infection.phar/src/Command/InfectionCommand.php:129
PHP   9. Infection\Process\Runner\MutationTestingRunner->run() phar://M:/Project/infection.phar/src/InfectionApplication.php:100
PHP  10. array_map() phar://M:/Project/infection.phar/src/Process/Runner/MutationTestingRunner.php:73
PHP  11. Infection\Process\Runner\MutationTestingRunner->Infection\Process\Runner\{closure}() phar://M:/Project/infection.phar/src/Process/Runner/MutationTestingRunner.php:73
PHP  12. Infection\Mutant\MutantCreator->create() phar://M:/Project/infection.phar/src/Process/Runner/MutationTestingRunner.php:65
PHP  13. Infection\Mutant\MutantCreator->isCoveredByTest() phar://M:/Project/infection.phar/src/Mutant/MutantCreator.php:66
PHP  14. Infection\TestFramework\Coverage\CodeCoverageData->hasExecutedMethodOnLine() phar://M:/Project/infection.phar/src/Mutant/MutantCreator.php:88
PHP  15. Infection\TestFramework\Coverage\CodeCoverageData->getCoverage() phar://M:/Project/infection.phar/src/TestFramework/Coverage/CodeCoverageData.php:83
PHP  16. file_get_contents() phar://M:/Project/infection.phar/src/TestFramework/Coverage/CodeCoverageData.php:147

Warning: file_get_contents(C:\Users\rjscully\AppData\Local\Temp/infection/coverage-xml/index.xml): failed to open stream: No such file or directory in phar://M:/Project/infection.phar/src/TestFramework/Coverage/CodeCoverageData.php on line 147
</details>

### Final state
After the output in the details expander above, the directory where index.xml is expected has two files:
- mutant.b4c682a2ff4ad6d0c73c07072e36dd87.infection.php (appears to be mutated code under test)
- phpunitConfiguration.initial.infection.xml (PHPUnit configuration with paths expanded)

However some expected artifacts don't exist:
- **coverage-xml does not exist**
- **phpunit.junit.xml does not exist**

**Comment by 3DFace** [comment] 2017-09-04 11:15
Hi @rjscully! I expirienced similar issue #24 few days ago.

Seems like `infection` creates config for initial `phpunit` run - `phpunitConfiguration.initial.infection.xml`, but coverage results are absent.

Try to run phpunit by yourself from command line with that config and post output here.
`phpunit -c C:\Users\rjscully\AppData\Local\Temp/infection/phpunitConfiguration.initial.infection.xml`
(correct actual config location if I wrong)

**Comment by rjscully** [comment] 2017-09-04 11:47
Hi @3DFace, thanks for the suggestion.

That command worked perfectly, and fixed the problem. And wow, infection is **_very_ fast**. With threading it's even faster than that, it's like magic.

```
Running initial test suite...

    1 [============================] < 1 sec

Generate mutants...

Processing source code files: 73/73
Creating mutated files and processes: 434/434
.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out

.SSSSSSSS.........................................   ( 50 / 434)
....................................S.............   (100 / 434)
..................................................   (150 / 434)
.......................................SS.........   (200 / 434)
...SSSSSSS..SS....SSS.....SSS.....................   (250 / 434)
..................................................   (300 / 434)
..................................................   (350 / 434)
..................................................   (400 / 434)
..................................                   (434 / 434)

434 mutations were generated:
     408 mutants were killed
      26 mutants were not covered by tests
       0 covered mutants were not detected
       0 time outs were encountered

Metrics:
         Mutation Score Indicator (MSI): 94%
         Mutation Code Coverage: 94%
         Covered Code MSI: 100%

Please note that some mutants will inevitably be harmless (i.e. false positives).

```

**Comment by 3DFace** [comment] 2017-09-04 12:23
>That command worked perfectly, and fixed the problem

I think it's OK for single run, bun not fixes a problem. By this way you'll need to rerun `phpunit` by hand after every code/test change. `Infection` should do it for you, but something goes wrong.

In my case it was caused by inappropriate `phpunit` binary found in my `PATH`.

Deeper investigation should be done. If you can to debug it then you should stop at `Finder/TestFrameworkExecutableFinder->find()` and examine `$this->cachedExecutable` value on method exit. 

I think someone from dev team can give you smarter advises, cause I'm not very expirienced with `infection`.

**Comment by borNfreee** [comment] 2017-09-04 20:24
I'm reopening this issue because the reason is still not found and there is definitely something wrong (with the infection itself or your environment).

@rjscully, since your project is not open sourced, I need your help.

1. I think that this is the same issue as @3DFace had with a different version of PHPUnit somewhere at your `PATH`. You can easily check it [setting the custom path to phpunit executable](https://infection.github.io/guide/usage.html#Configuration). Just set `customPath` for debug purpose to correct PHPUnit, remove all files from `C:\Users\rjscully\AppData\Local\Temp/infection/` and run infection again.

2. If this will still give an error, could you please dump the result of `Infection\Finder\TestFrameworkExecutableFinder->find()`as suggested above?

3. Also, `Covered Code MSI: 100%` seems very suspicious, could you please examine the `infection-log.txt` and see whether there are fatal errors for each mutation (which is identified as *killed*) or not. Probably, you can past it to e.g. Pastebin and post link here, I will investigate it either

--------

> Note: The GitHub issue template suggests enclosing the following XML block in a details expander, but GitHub does not appear to support backtick quoting within the context of a details expander.

It's possible to use code blocks inside `details` tag. I've modified your initial comment.

I've also create an enhancement ticket to add PHPUnit/PhpSpec version information to the console to detect such issues instantly

**Comment by rjscully** [comment] 2017-09-04 22:56
Purging the temp folder _does_ reset to the original (broken) state.

$this->cachedExecutable's value is a command containing the full path to php.exe with the PHPUnit PHAR's full path as an argument (example below). When run, this command does successfully execute PHPUnit.

```
c:\bin\php\php.exe C:\bin\phpunit\phpunit-6.2.4.phar
```

💯 MSI is fine, no fatal errors. Humbug reports the same.

**Comment by borNfreee** [comment] 2017-09-04 23:03
Then I don't understand how the same command works when executed manually and does not work when executed by infection :|

It would be awesome if you find some time and create a very small github test project where this issue can be reproduced (e.g. 1 class, 1 test). Then I will dig to the problem myself.

Am I right that you are experiencing this issue only on windows?

**Comment by rjscully** [comment] 2017-09-05 00:11
I might've gotten sidetracked when checking after setting up PHPUnit in the config. During that setup I encountered an error but then realized it was due to traditional Windows paths (containing backslashes making it an invalid path), and after writing that up I'm not sure I did re-run infection cleanly without dump/exit code.

With PHPUnit explicitly defined, when I run infection I get this timeout:

<details>
<summary>Output with PHPUnit explicitly defined</summary>

```
[Symfony\Component\Process\Exception\ProcessTimedOutException]                                                                                                                                                                      
  The process "c:\bin\php\php.exe C:\bin\phpunit\phpunit-6.2.4.phar --configuration C:\Users\rjscully\AppData\Local\Temp/infection/phpunitConfiguration.initial.infection.xml --stop-on-failure" exceeded the timeout of 10 seconds.  
```

</details>

With PHPUnit explicitly defined and timeout set to 500, infection runs. It's also a bit slower now, but I suppose that's a good thing if prior results were inaccurate.

The output from infection is different now, containing escaped mutations. Humbug does not detect any escaped mutations, however infection has 434 total mutations and Humbug only has 294. The types of mutations I see are not explored in Humbug. For example, many of the escaped mutations are the method visibility variant.

<details>
<summary>Output with timeout=500 and PHPUnit customPath set</summary>

```
Running initial test suite...

   90 [============================]  1 min

Generate mutants...

Processing source code files: 73/73
Creating mutated files and processes: 434/434
.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out

.SSSSSSSS...M.....................................   ( 50 / 434)
......................MM............S.............   (100 / 434)
..................................................   (150 / 434)
.........................M............MSS.........   (200 / 434)
.M.SSSSSSS.MSS.M.MSSS.....SSS.....................   (250 / 434)
..M..........MM...M...............................   (300 / 434)
..................................................   (350 / 434)
..................................................   (400 / 434)
.MMM....M.................M.......                   (434 / 434)

434 mutations were generated:
     390 mutants were killed
      26 mutants were not covered by tests
      18 covered mutants were not detected
       0 time outs were encountered

Metrics:
         Mutation Score Indicator (MSI): 90%
         Mutation Code Coverage: 94%
         Covered Code MSI: 96%

Please note that some mutants will inevitably be harmless (i.e. false positives).
```

</details>

**Comment by borNfreee** [comment] 2017-09-15 17:39
> With PHPUnit explicitly defined, when I run infection I get this timeout

Should be fixed in 0.5.3

> Humbug does not detect any escaped mutations, however infection has 434 total mutations and Humbug only has 294.

That's expected because humbug has different set of mutation operators.

> For example, many of the escaped mutations are the method visibility variant.

There is also some enhancements in 0.5.3 for this mutator. So please try new version.

----------

Returning to your original question. Could you please remove tmp infection folder, remove custom PHPUnit path from the infection config and try to run 0.5.3 for your project? It will show executed PHPUnit version to the console.

Please post infection-log.txt here (or to pastebin) if you have any problems.

**Comment by rjscully** [comment] 2017-09-16 15:02
With the tmp folder removed and the phpUnit configuration element absent the following output is returned:
<details>
  <summary>Output without phpUnit element in infection.json.dist</summary>

  ```
  [InvalidArgumentException]                              
  Parameter does not contain a valid SemVer (sub)string.
  ```
</details>

------

With the phpUnit element in place in the infection.json.dist, infection appears to run correctly.

**Comment by borNfreee** [comment] 2017-10-28 01:22
Closing this because 99% you have something wrong with PATH and phpunit executable.

Feel free to reopen if you can reproduce it on *different* machines.
Also, there is a slack group - https://symfony-devs.slack.com/messages/C78M7A4BY - we can have an online chat instead of posting multiple messages here

**Closed by borNfreee** 2017-10-28 01:22 UTC
