### ISSUE TITLE
I see PHPUnit version: unknown

### ISSUE THREAD

**Issue by marcelloh** [infection/infection#515] opened 2018-10-20 08:23 UTC
When I start the infection, it states:
PHPUnit version: unknown

Which is strange, because I can see I have (and use) phpUnit.

Does it mean, phpunit is not used?
that should explain the tons of blue 'S's I see on my screen.

**Comment by borNfreee** [comment] 2018-10-21 05:57
Hi, thanks for opening this issue. However, there is not enough information to understand what is going on. 

Could you please

* create a public repository where this issue can be reproduced or
* give us more details about what Infection version are you using, what PHP and PHPUnit version
* what does your `phpunit.xml` look like 

There can be tens of reasons. Unfortunately, without source code it's hard to say what is wrong.

> Does it mean, phpunit is not used?

No, PHPUnit is used, I think the issue is with CodeCoverage and `phpunit.xml` configuration.

**Comment by borNfreee** [comment] 2018-11-05 19:56
ping @marcelloh

**Comment by marcelloh** [comment] 2018-11-06 08:35
Sorry but I can't give you any reproducable source code.
0.10.6 is the version (but it would be handy if that was shown somewhere on the start)
PHPUnit 7.4.3

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         bootstrap="../vendor/autoload.php"
         columns="42"
        >
    <testsuites>
        <testsuite name="Smart Test Suite : ALL">
            <directory>../tests/Initial</directory>
            <directory>../tests/Unit</directory>
            <directory>../tests/Functional</directory>
            <directory>../tests/Last</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist>
            <directory>./../init</directory>
            <directory>./../src</directory>
        </whitelist>
    </filter>
</phpunit>
```

**Comment by sanmai** [comment] 2018-11-06 10:04
By any chance, do you have TLS disabled for Composer? See #516

**Comment by marcelloh** [comment] 2018-11-06 12:35
Nope, I just get "vendor/bin", nothing more

**Comment by siad007** [comment] 2019-01-14 12:05
@marcelloh could you post your command line you use to start infection and your folder tree of your project? It seems to me, that your `phpunit.xml` is located under a subfolder rather than on the root. So it could be possible, that the xml cannot be found.

**Comment by marcelloh** [comment] 2019-01-14 13:01
It is true, that my phpunit.xml is in a subfolder.
```
php -d xdebug.remote_enable=1 -d xdebug.remote_autostart=On -d xdebug.idekey=Intellij ./vendor/infection/infection/bin/infection -j5 --ansi -vvv
```
and for my phpunit tests, I always give this bit extra to the command line:
```
-c tests/phpunit.xml
```

**Comment by borNfreee** [comment] 2019-01-14 13:08
Could you also show `infection.json` contents?
Have you tried to configure a location of PHPUnit's config file?

See `phpUnit.configDir` settings in https://infection.github.io/guide/usage.html

**Comment by marcelloh** [comment] 2019-01-14 13:10
This is ours, and as you can see, I have a configDir
```
{
    "source": {
        "directories": [
            "./src"
        ]
    },
    "timeout": 5,
    "logs": {
        "text": "./infection/infection-log.txt",
        "summary": "./infection/summary-log.txt",
        "debug": "./infection/debug-log.txt"
    },
    "tmpDir": "./infection/temp",
    "phpUnit": {
        "configDir": "tests"
    },
    "mutators": {
        "@default": true,
        "@operator": false,
        "IdenticalEqual": false,
        "NotIdenticalNotEqual": false
    }
}
```

**Comment by maks-rafalko** [comment] 2021-08-10 21:21
is it still an issue @marcelloh ?

**Comment by MarcelXia** [comment] 2021-08-11 10:12
have no clue, I left the php community  sometime ago

**Comment by maks-rafalko** [comment] 2021-08-11 11:35
I hope you are enjoying your new language/community and continue using Mutation Testing there ;)

Ok then, closing as there were no similar complains

**Closed by maks-rafalko** 2021-08-11 11:35 UTC
Labels: Waiting Response
