### ISSUE TITLE
Error: Expected a value other than null.

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#1480] opened 2021-02-11 19:56 UTC
I get this error too. I'm a brand new user and have infection/infection 0.21.0@dfacb1e3d9def7fd34c6fb8df4d4bd098815dc82 PHPUnit version 8.5.14 PHP 7.4.15 Xdebug 3.0.2 codebase is CakePHP 4.2.2. 

```
challgren@challgren-pro authenticon-web %  XDEBUG_MODE=coverage; vendor/bin/infection

    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Infection - PHP Mutation Testing Framework version 0.21.0@dfacb1e3d9def7fd34c6fb8df4d4bd098815dc82


Running initial test suite...

PHPUnit version: 8.5.14

  173 [============================] 19 secs

Generate mutants...

Processing source code files: 33/36
In Assert.php line 2042:
                                     
  Expected a value other than null.  
                                     

run [--test-framework TEST-FRAMEWORK] [--test-framework-options TEST-FRAMEWORK-OPTIONS] [-j|--threads THREADS] [--only-covered] [-s|--show-mutations] [--no-progress] [--force-progress] [-c|--configuration CONFIGURATION] [--coverage COVERAGE] [--mutators MUTATORS] [--filter FILTER] [--formatter FORMATTER] [--git-diff-filter GIT-DIFF-FILTER] [--git-diff-base GIT-DIFF-BASE] [--logger-github] [--noop] [--min-msi MIN-MSI] [--min-covered-msi MIN-COVERED-MSI] [--log-verbosity LOG-VERBOSITY] [--initial-tests-php-options INITIAL-TESTS-PHP-OPTIONS] [--skip-initial-tests] [--ignore-msi-with-no-mutations] [--debug] [--dry-run]


```

See details https://github.com/infection/infection/issues/1357#issuecomment-777754308

_Originally posted by @challgren in https://github.com/infection/infection/issues/1357#issuecomment-777741442_

**Comment by challgren** [comment] 2021-02-12 03:23
```
XDEBUG_MODE=coverage; vendor/bin/infection --log-verbosity=all -vvv
[debug] Checking INFECTION_ALLOW_XDEBUG
[debug] The Xdebug extension is loaded (3.0.2)
[debug] Async signals enabled (SIGINT = SIG_IGN)
[debug] Process restarting (INFECTION_ALLOW_XDEBUG=internal|3.0.2|1|*|*)
[debug] Running '/usr/local/Cellar/php@7.4/7.4.15/bin/php' 'vendor/bin/infection' '--log-verbosity=all' '-vvv' '--ansi'
[debug] Checking INFECTION_ALLOW_XDEBUG
[debug] Restarted (83 ms). The Xdebug extension is not loaded
[debug] Async signals enabled (SIGINT = SIG_DFL)

    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Infection - PHP Mutation Testing Framework version 0.21.0@dfacb1e3d9def7fd34c6fb8df4d4bd098815dc82


Running initial test suite...

PHPUnit version: 8.5.14

  173 [============================] 15 secs

Generate mutants...

Processing source code files: 33/36
In Assert.php line 2042:
                                     
  [InvalidArgumentException]         
  Expected a value other than null.  
                                     

Exception trace:
  at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/webmozart/assert/src/Assert.php:2042
 Webmozart\Assert\Assert::reportInvalidArgument() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/webmozart/assert/src/Assert.php:600
 Webmozart\Assert\Assert::notNull() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/TestFramework/Coverage/ProxyTrace.php:122
 Infection\TestFramework\Coverage\ProxyTrace->getTestLocator() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/TestFramework/Coverage/ProxyTrace.php:111
 Infection\TestFramework\Coverage\ProxyTrace->getAllTestsForMutation() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/Mutator/NodeMutationGenerator.php:182
 Infection\Mutator\NodeMutationGenerator->getAllTestsForCurrentNode() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/Mutator/NodeMutationGenerator.php:135
 Infection\Mutator\NodeMutationGenerator->generateForMutator() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/Mutator/NodeMutationGenerator.php:112
 Infection\Mutator\NodeMutationGenerator->generate() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/PhpParser/Visitor/MutationCollectorVisitor.php:80
 Infection\PhpParser\Visitor\MutationCollectorVisitor->getMutations() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/Mutation/FileMutationGenerator.php:109
 Infection\Mutation\FileMutationGenerator->generate() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/Mutation/MutationGenerator.php:101
 Infection\Mutation\MutationGenerator->generate() at n/a:n/a
 iterator_to_array() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/IterableCounter.php:64
 Infection\IterableCounter::bufferAndCountIfNeeded() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/Process/Runner/MutationTestingRunner.php:100
 Infection\Process\Runner\MutationTestingRunner->run() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/Engine.php:171
 Infection\Engine->runMutationAnalysis() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/Engine.php:111
 Infection\Engine->execute() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/Command/RunCommand.php:342
 Infection\Command\RunCommand->executeCommand() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/src/Command/BaseCommand.php:75
 Infection\Command\BaseCommand->execute() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /Users/challgren/Projects/truepedigree/authenticon-web/vendor/infection/infection/bin/infection:83

run [--test-framework TEST-FRAMEWORK] [--test-framework-options TEST-FRAMEWORK-OPTIONS] [-j|--threads THREADS] [--only-covered] [-s|--show-mutations] [--no-progress] [--force-progress] [-c|--configuration CONFIGURATION] [--coverage COVERAGE] [--mutators MUTATORS] [--filter FILTER] [--formatter FORMATTER] [--git-diff-filter GIT-DIFF-FILTER] [--git-diff-base GIT-DIFF-BASE] [--logger-github] [--noop] [--min-msi MIN-MSI] [--min-covered-msi MIN-COVERED-MSI] [--log-verbosity LOG-VERBOSITY] [--initial-tests-php-options INITIAL-TESTS-PHP-OPTIONS] [--skip-initial-tests] [--ignore-msi-with-no-mutations] [--debug] [--dry-run]

[debug] Restarted process exited 1
```

As for the file thats breaking, I have no clue. This is my first run with infection/infection so you'd have to help guide me to find the problem code. I can tell you its a CakePHP 4.2.2 application

**Comment by AlexandruGG** [comment] 2021-02-27 14:07
I'm seeing this as well on a fresh Symfony 5.2 + PHP 8 installation, running with PHPUnit 9.5, and PCOV. 

The stack trace is identical. I tried debugging a bit because I only have a few files. It fails in Entities and Repositories, although if I remove any getters and setters from the entity it works. In the repository, it only works if I remove the constructor.

**Comment by maks-rafalko** [comment] 2021-02-27 21:34
can I ask you to post the content of those files here? Are you able to reproduce it on our [Playground](https://infection-php.dev/)?

**Comment by AlexandruGG** [comment] 2021-02-28 23:12
> can I ask you to post the content of those files here? Are you able to reproduce it on our [Playground](https://infection-php.dev/)?

I tried reproducing it in the playground without success. Nonetheless here is an example of an entity that is causing it to break. I stripped it to the minimum that still breaks Infection:

```PHP
<?php

declare(strict_types=1);

namespace App\Infrastructure\Core\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Infrastructure\Core\Repository\UserRepository;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 */
class User
{
    /**
     * @ORM\Column(name="id", type="integer", nullable=false, options={"unsigned"=true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private int $id;
    
    public function getId(): int
    {
        return $this->id;
    }
}
```

There's nothing special about it so I'm thinking the problem must be elsewhere

**Comment by AlexandruGG** [comment] 2021-02-28 23:28
Here's something else I found:
- I was looking at the history of changes done in [ProxyTrace](https://github.com/infection/infection/blob/master/src/TestFramework/Coverage/ProxyTrace.php) and I noticed this PR https://github.com/infection/infection/pull/1435
- based on the time of merge of that PR, I tried running with infection release `0.20.2` rather than latest and **it works**!
- if I try `0.21.0` it **fails** with the error mentioned

Based on this I suspect it's an issue introduced by that PR?

**Comment by sanmai** [comment] 2021-03-01 10:48
It's despicable it took me three weeks to get around at this issue. Should be fixed by #1494. 

If  anyone wishes to give it a shot, please be our guest.

**Closed** 2021-03-01 20:00 UTC
Labels: Bug

**Comment by maks-rafalko** [comment] 2021-03-01 20:07
@challgren @AlexandruGG released as https://github.com/infection/infection/releases/tag/0.21.3

Thank you @sanmai

**Comment by challgren** [comment] 2021-03-01 20:09
Ok cool thanks @sanmai I'll try it again once I get my project refactored so it will be a couple days before I can report back.

**Comment by AlexandruGG** [comment] 2021-03-01 20:36
@sanmai thank you very much for the speedy fix! I can confirm everything works now with the latest release 🎉
