### ISSUE TITLE
CTRL+C does not terminate process in progress

### ISSUE THREAD

**Issue by Bilge** [infection/infection#806] opened 2019-10-17 21:21 UTC
CTRL+C interrupt is ignored by the program from start to finish and cannot be used to abort execution. Would be nice to have this ability.

**Comment by sanmai** [comment] 2019-10-17 22:32
So far I cannot reproduce the issue with ignored CTRL+C. Infection stop just as I type that combination. Is there a repository where this behaviour can be seen?

**Comment by Bilge** [comment] 2019-10-17 23:20
Under mintty on Windows 10.

**Comment by sanmai** [comment] 2019-10-17 23:22
It is highly doubtful that Infection has anything to do with this behaviour. For one, because `pcntl_signal`, which is typically used to ignore signals, is never used.

**Comment by BackEndTea** [comment] 2019-10-18 06:47
Its been a while since i did anything windows command line, but isn't ctrl+c just a copy there?

**Comment by BackEndTea** [comment] 2019-10-18 08:24
Guess that just shows my ignorance of windows command line then. In that case i must admit i have no clue why ctrl c wouldn't abort like it is supposed to do.

**Comment by theofidry** [comment] 2019-10-18 15:39
@Bilge the question is more what could prevent Windows to stop the command... We are not doing anything fancy there. Intercepting signals requires `pcntl` which we never use (and it won't work on Windows anyway).

Is this the case at any point of execution of Infection or is it in a specific phase?

**Comment by theofidry** [comment] 2019-10-18 15:43
Can you try with `-vvv` and post the log? I'm curious to know if that could be because the infection process would restart itself to disable xdebug

**Comment by maks-rafalko** [comment] 2019-11-13 14:49
ping @Bilge

**Comment by Bilge** [comment] 2019-11-13 18:01
I'm not sure what you mean. `-vvv` does not change the output in any way.

**Comment by maks-rafalko** [comment] 2021-03-02 20:10
closing as no one complains about it and we couldn't reproduce it

**Closed by maks-rafalko** 2021-03-02 20:10 UTC
Labels: Bug, Waiting Response
