### ISSUE TITLE
Starting infection via phing differs from commandline

### ISSUE THREAD

**Issue by marcelloh** [infection/infection#592] opened 2018-12-19 10:21 UTC
I have a commandline (windows-batchfile) which does the following.
```
C:\somedir\php.exe -n -c C:\Users\Marcelloh\AppData\Local\Temp\A4D0.tmp ./vendor/infection/infection/bin/infection -j5 --ansi"
```
or when I run it via the tool "phing", it's the same command (where only the config file is changed)

In both situations, In the XdebugHandler, it goes to
```
            if ($this->prepareRestart()) {
                $command = $this->getCommand();
                $this->notify(Status::RESTARTING, $command);
                $this->restart($command);
            }
```
but started via phing, it stops and says the following:
```
In CoverageDoesNotExistException.php line 22:
Code Coverage does not exist. File C:\myproject/./infection/temp/infection/coverage-xml/index.xml is not found. 
```
In both situations, there is a phpunit.junit.xml generated with the same content (only the times differ)

Is there anyone who managed to run this via Phing?

**Comment by BackEndTea** [comment] 2018-12-19 10:43
Looking at the error message `C:\myproject/./infection/temp/infection/coverage-xml/index.xml` looks off. I think there is an error in the generation of the path to the file.

**Comment by marcelloh** [comment] 2018-12-19 10:46
the beginning of the path is not off, but the "coverage-xml/index.xml" is not generated. (it is in the commandline verion). So how do I generate that (via infection)

**Comment by marcelloh** [comment] 2019-01-02 13:18
Just the part of the phing file where it is configured
```
	<target name="infection">
		<echo level="warning" msg="infection" />
		<exec executable="${PHP_HOME}" passthru="true" escape="false">
			<arg value="./vendor/infection/infection/bin/infection" />
			<arg value="-j5" />
			<arg value="--ansi" />
		</exec>
	</target>

```

**Comment by siad007** [comment] 2019-01-02 14:05
@marcelloh what is the content of `${PHP_HOME}` and which version of phing do you use? It could also be of help to use phing in debug mode. I cannot reproduce your problem. BTW I will start development an inflection task at phing.

**Comment by marcelloh** [comment] 2019-01-02 15:19
that is the location where my php is installed (So I can easily switch versions)
```
C:\Development\php\php-7.2.12-nts-Win32-VC15-x64\php.exe
```

**Comment by marcelloh** [comment] 2019-01-02 15:30
Phing 3.0.0-alpha1
and I invoke it from within another script with require_once
(so I can I set it in debug mode?)

**Comment by siad007** [comment] 2019-01-02 15:38
It looks like the the property was not expanded or was not set correctly. Can you insert a `<echo>${PHP_HOME}</echo>`

**Comment by marcelloh** [comment] 2019-01-02 15:43
That is wierd. In my infection task, it won't echo a thing, but in another task it does.
(and the php_home is initialized in the top somewhere)

**Comment by siad007** [comment] 2019-01-02 15:45
I think your problem is not related to inflection. Can you post your entire build.xml at [phing](https://github.com/phingofficial/phing/issues) .

**Comment by marcelloh** [comment] 2019-01-02 15:57
```
<?xml version="1.0" encoding="utf-8"?>
<project name="SMART" description="SMART Command Line Interface" default="?">

	<property name="PHP_HOME" value=" C:\Development\php\php-7.2.12-nts-Win32-VC15-x64\php.exe" />

	<target name="infection">
		<echo level="warning" msg="${PHP_HOME}"/>

		<echo level="warning" msg="remove infection" />
		<delete dir="infection" includeemptydirs="true" />

		<echo level="warning" msg="infection" />

		<echo>${PHP_HOME}</echo>
		<echo level="warning" msg="phphome is [${PHP_HOME}] between brackets" />
		<exec executable="${PHP_HOME}" passthru="true" escape="false">
			<arg value="./vendor/infection/infection/bin/infection" />
			<arg value="-j5" />
			<arg value="--ansi" />
		</exec>
	</target>

	<target name="?">
		<echo level="" msg="${line.separator}
		${PHP_HOME} ${line.separator}
		------ ${line.separator}
		" />
	</target>
</project>
```

**Comment by siad007** [comment] 2019-01-02 16:00
> Can you post your entire build.xml at [phing](https://github.com/phingofficial/phing/issues)?

I think your problem is the usage of phing, so we should move to the right place.

**Comment by siad007** [comment] 2019-01-02 19:55
@borNfreee @BackEndTea we here on phing could confirm that there is no issue with invoking infection through phing. A small test succseeded with the following [result](https://github.com/phingofficial/phing/issues/1013#issuecomment-450961553)

**Comment by borNfreee** [comment] 2019-01-15 20:54
> @borNfreee @BackEndTea we here on phing could confirm that there is no issue with invoking infection through phing

Closing for now until we have a reproducible repository with the issue.

**Closed by borNfreee** 2019-01-15 20:54 UTC
Labels: bug, not confirmed
