### ISSUE TITLE
Problem with autoload PHPUnit classes with simple-phpunit

### ISSUE THREAD

**Issue by gcrispyn** [infection/infection#829] opened 2019-11-14 09:44 UTC
| Question    | Answer
| ------------| ---------------
| Infection version | 0.14.25
| Test Framework version | PHPUnit
| PHP version | 7.3.11
| Platform    | Windows
| Repo | Private

Hi there, I have an issue with Infection when I use simple-phpunit wia symfony/phpunit-bridge.

This is the output of Infection :

```
You are running Infection with Xdebug enabled.
     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

    0 [>---------------------------] < 1 sec
Running initial test suite...

PHPUnit version: 6.5.14

   22 [============================] 24 secs

Generate mutants...

Processing source code files: 7/8PHP Fatal error:  Uncaught Error: Class 'PHPUnit\Framework\TestCase' not found in K:\RC\tests\Service\DatagridServiceTest.php:70
Stack trace:
#0 K:\RC\vendor\composer\ClassLoader.php(447): include()
#1 K:\RC\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('K:\\RC\\vendor\\co...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Tests\\Service\\D...')
#3 [internal function]: spl_autoload_call('Tests\\Service\\D...')
#4 K:\RC\vendor\infection\infection\src\Visitor\ReflectionVisitor.php(81): ReflectionClass->__construct('Tests\\Service\\D...')
#5 K:\RC\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(200): Infection\Visitor\ReflectionVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#6 K:\RC\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#7 K:\RC\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#8 K:\RC\vendor\nikic\php-parser\lib\P in K:\RC\tests\Service\DatagridServiceTest.php on line 70
```

Sounds like a problem with autoloading PHPUnit classes.

Can you help me?

**Comment by maks-rafalko** [comment] 2019-11-14 09:58
Hi, thanks for creating an issue. It would be much faster resolved if you provide a reproducible example (minimal repository) that we can use to debug the issue.

As I mentioned on twitter, we [have an end-to-end test](https://github.com/infection/infection/tree/master/tests/e2e/SymfonyBridge) that shows it should work. Probably the issue is in the versions of `symfony/phpunit-bridge` and/or PHPUnit, who knows ;)

So please try to extract a repository

**Comment by maks-rafalko** [comment] 2019-12-12 04:44
Closing as you didn't respond. Feel free to reopen with reproducible case.

**Closed by maks-rafalko** 2019-12-12 04:44 UTC
Labels: bug, not confirmed, waiting response
