### ISSUE TITLE
Idea: Mitigate equivalent mutants issue

### ISSUE THREAD

**Issue by patrickfunke** [infection/infection#127] opened 2018-01-16 14:31 UTC
To better argument how reliable the generated Mutation Score results are, it is important to know about the equivalent mutant problem. As far as I've seen, Infection does not yet implement any countermeasures to address equivalent mutants. This causes possibly far off results.

Research proposes various approaches and heuristics to handle the problem of equivalent mutants. Would it be feasible to include such an approach into the framework? It could improve the trust in the MSI by a lot.

**Comment by maks-rafalko** [comment] 2019-06-19 18:45
A little bit confused by this issue. 

What exactly (algorithm) should we implement? 
What are equivalent mutations do you have in your projects?

Now this issue looks like a "dead" one. It's not clear what to do, where to start, what exactly to fix.

**Comment by maks-rafalko** [comment] 2019-06-19 18:48
I would rather start with putting here real examples of equivalent mutations.

```diff
- $a = -1 * $b;
+ $a = -1 * $b;
```

this is a simple one, and we've fixed it

**Comment by theofidry** [comment] 2019-06-19 23:10
>Research proposes various approaches and heuristics to handle the problem of equivalent mutants. 

I would also argue that like mbj, most of the paperwork researchs promoting equivalent mutant detection, offer _no reproduceable case study_ which completely invalidates their results. Talking with mbj, it seems most of the time redudant mutants are a case of the mutation testing tool trying to mutatte the code in every possible way rather, including by making the mutated code looser than the original code, rather than trying to make it stricter.

We can't provide numbers yet, but I'm sure after a revision of Infection's mutators between trying to make the code stricter or more correct instead of genuinely introducing any kind of mutants (e.g. transforming `===` to `==`) - which is already in the way!, we will see serious improvements in terms of redundancy.

**Comment by maks-rafalko** [comment] 2019-06-23 12:30
Let's close this one since there is no concrete issue and no concrete solution.

**Closed by maks-rafalko** 2019-06-23 12:30 UTC
Labels: RFC
