### ISSUE TITLE
Source files outside the src folder always skipped

### ISSUE THREAD

**Issue by Landerstraeten** [infection/infection#57] opened 2017-10-25 06:36 UTC
| Question    | Answer
| ------------| ---------------
| Infection version | 0.6.0
| Test Framework version | PhpSpec 4.1.0
| PHP version | 7.1.8
| Platform    | MacOS
| Github project | https://github.com/Landerstraeten/infection-poc

I try to use infection in a reusable Symfony bundle. Thereby live the source files not under the src folder, but in the root of the project. Apparently this is not working with infection.

I've created a [dummy project](https://github.com/Landerstraeten/infection-poc) with both the working and not working version.

Feel free to comment or even PR the solution.

Thanks!

``` bash
$ bin/infection --test-framework=phpspec
```
<details>
 <summary>Output source files: root folder</summary>
 
 ```
Running initial test suite...

Phpspec version: 4.1.0

    4 [============================] < 1 sec

Generate mutants...

Processing source code files: 2/2
Creating mutated files and processes: 3/3
.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out

SSS                                                  (3 / 3)

3 mutations were generated:
       0 mutants were killed
       3 mutants were not covered by tests
       0 covered mutants were not detected
       0 time outs were encountered

Metrics:
         Mutation Score Indicator (MSI): 0%
         Mutation Code Coverage: 0%
         Covered Code MSI: 0%

Please note that some mutants will inevitably be harmless (i.e. false positives).
 ```
</details>

<details>
 <summary>Output source files: src folder</summary>
 
 ```
Running initial test suite...

Phpspec version: 4.1.0

    4 [============================]  1 sec

Generate mutants...

Processing source code files: 1/1
Creating mutated files and processes: 1/1
.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out

.                                                    (1 / 1)

1 mutations were generated:
       1 mutants were killed
       0 mutants were not covered by tests
       0 covered mutants were not detected
       0 time outs were encountered

Metrics:
         Mutation Score Indicator (MSI): 100%
         Mutation Code Coverage: 100%
         Covered Code MSI: 100%

Please note that some mutants will inevitably be harmless (i.e. false positives).
 ```
</details>

**Comment by borNfreee** [comment] 2017-10-25 20:09
First of all, thank you for creating this issue with the reproducible repository, it helped a lot.

The reason of this bug was an error in the logic that generates initial YAML config for PHPSpec. It removed `whitelist` section from your config, thus no CodeCoverage was generated and all mutants were considered "not covered".

Fixed in #59 .

PS: `master branch` of your repository does not work, I had to tweak PSR-4 section in `compsoser.json` to load classes properly.

Also, there is no need to mutate specs folder. So I've exluded them.

```diff
diff --git a/composer.json b/composer.json
index 37693d1..147285c 100644
--- a/composer.json
+++ b/composer.json
@@ -9,7 +9,7 @@
   ],
   "autoload": {
     "psr-4": {
-      "Foo\\Bar\\": ""
+      "": ""
     }
   },
   "config": {
diff --git a/infection.json.dist b/infection.json.dist
index 7598791..003561d 100644
--- a/infection.json.dist
+++ b/infection.json.dist
@@ -3,6 +3,10 @@
     "source": {
         "directories": [
             "."
+        ],
+        "exclude": [
+            "spec",
+            "vendor"
         ]
     },
     "logs": {
```

**Closed** 2017-10-25 20:12 UTC
Labels: bug, has PR
