### ISSUE TITLE
Phar does not work after Box prefixing

### ISSUE THREAD

**Issue by maks-rafalko** [infection/infection#795] opened 2019-09-22 11:09 UTC
I tested the latest [phar](https://github.com/infection/infection/releases/download/0.14.0/infection.phar) generated for 0.14.0 release and it does not work:

```php
You are running Infection with PCOV enabled.
     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

PHP Fatal error:  Uncaught Error: Call to undefined function _HumbugBoxc963874314ce\Safe\sprintf() in phar:///tmp/infection.phar/src/Locator/FileNotFound.php:15
Stack trace:
#0 phar:///tmp/infection.phar/src/Locator/RootsFileOrDirectoryLocator.php(37): _HumbugBoxc963874314ce\Infection\Locator\FileNotFound::fromFileName('infection.json', Array)
#1 phar:///tmp/infection.phar/src/Locator/RootsFileOrDirectoryLocator.php(53): _HumbugBoxc963874314ce\Infection\Locator\RootsFileOrDirectoryLocator->locate('infection.json')
#2 phar:///tmp/infection.phar/src/Locator/RootsFileOrDirectoryLocator.php(41): _HumbugBoxc963874314ce\Infection\Locator\RootsFileOrDirectoryLocator->innerLocateOneOf(Array)
#3 phar:///tmp/infection.phar/src/Command/InfectionCommand.php(166): _HumbugBoxc963874314ce\Infection\Locator\RootsFileOrDirectoryLocator->locateOneOf(Array)
#4 phar:///tmp/infection.phar/src/Command/InfectionCommand.php(72): _HumbugBoxc963874314ce\Infection\Command\InfectionCommand->runConfigurationCommand(Object(_HumbugBoxc963874314ce\Infection\ in phar:///tmp/infection.phar/src/Locator/FileNotFound.php on line 15

Fatal error: Uncaught Error: Call to undefined function _HumbugBoxc963874314ce\Safe\sprintf() in phar:///tmp/infection.phar/src/Locator/FileNotFound.php:15
Stack trace:
#0 phar:///tmp/infection.phar/src/Locator/RootsFileOrDirectoryLocator.php(37): _HumbugBoxc963874314ce\Infection\Locator\FileNotFound::fromFileName('infection.json', Array)
#1 phar:///tmp/infection.phar/src/Locator/RootsFileOrDirectoryLocator.php(53): _HumbugBoxc963874314ce\Infection\Locator\RootsFileOrDirectoryLocator->locate('infection.json')
#2 phar:///tmp/infection.phar/src/Locator/RootsFileOrDirectoryLocator.php(41): _HumbugBoxc963874314ce\Infection\Locator\RootsFileOrDirectoryLocator->innerLocateOneOf(Array)
#3 phar:///tmp/infection.phar/src/Command/InfectionCommand.php(166): _HumbugBoxc963874314ce\Infection\Locator\RootsFileOrDirectoryLocator->locateOneOf(Array)
#4 phar:///tmp/infection.phar/src/Command/InfectionCommand.php(72): _HumbugBoxc963874314ce\Infection\Command\InfectionCommand->runConfigurationCommand(Object(_HumbugBoxc963874314ce\Infection\ in phar:///tmp/infection.phar/src/Locator/FileNotFound.php on line 15
```

However, PHAR file contains this function when I open it in PHPStorm

`/infection.phar/vendor/thecodingmachine/safe/generated/strings.php`

<img width="707" alt="infection  ~:sites:infection  -  :infection phar:vendor:thecodingmachine:safe:generated:strings php 2019-09-22 14-08-09" src="https://user-images.githubusercontent.com/3725595/65386294-81fe0880-dd42-11e9-88b5-7a4d36a90005.png">

cc @theofidry

**Comment by maks-rafalko** [comment] 2019-09-22 15:02
tried to temporary skip `Safe\*` namespace prefixing, but get another issue. Reported to `humbug/box` https://github.com/humbug/box/issues/439

**Comment by maks-rafalko** [comment] 2019-09-23 14:59
It is reproducing when I run PHAR for infection itself. For other small test projects it works fine. Still need to understand why, but it's not critical I think

**Comment by theofidry** [comment] 2019-09-23 15:03
Will try to have a look this week

**Comment by theofidry** [comment] 2019-12-05 09:42
Fixed with #851

**Comment by maks-rafalko** [comment] 2019-12-07 09:58
Still does not work.

Steps to reproduce:

```bash

git checkout master
git pull --rebase

make compile

# run PHAR for itself
build/infection.phar
```

Results to:

```bash
$ build/infection.phar
You are running Infection with PCOV enabled.

    ____      ____          __  _
   /  _/___  / __/__  _____/ /_(_)___  ____
   / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
 _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
/___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Infection - PHP Mutation Testing Framework dev-master@1d79de53cbc1dfa902e1ea4afba6c3f0214d5224
PHP Fatal error:  Uncaught Error: Call to undefined function _HumbugBoxd3fcd7816585\Safe\sprintf() in phar:///infection/build/infection.phar/src/Locator/FileOrDirectoryNotFound.php:15
Stack trace:
```

**Comment by theofidry** [comment] 2020-02-23 23:54
Note to myself regarding the current status: the issue is autoloading: Infection autoload the project autoloader + its own autoloader. However for files this causes an issue, see https://github.com/humbug/php-scoper/issues/298

**Closed** 2020-02-25 07:28 UTC
Labels: Bug, Has PR
