### ISSUE TITLE
If condition negation mutator

### ISSUE THREAD

**Issue by manhunto** [infection/infection#1752] opened 2022-11-18 17:14 UTC
**Is your feature request related to a problem? Please describe.**
Hello, I was surprised that infection doesn't support the negation of the whole `if` statement. For example, there is code like this

```php
if ($this->someMethodCall()) {
}
````

And any mutation wasn't mutate this code.

I expected that my code would be mutated into this

```php
if (!($this->someMethodCall())) {
}
````

There is a mutation that negates my condition but only when I write code like this, but I usually skip `=== true`.

```php
if ($this->someMethodCall() === true) {
}
````

**Describe the solution you'd like**
I cloned the infection repository, and I've tried to implement it, and I have POC of some conditions that can be mutated. But I want to know before the final implementation, there were some attempts to implement it, and it failed. Or maybe there are some other cases that I don't know now :)

Thank you, and have a good day!

**Comment by maks-rafalko** [comment] 2022-11-19 09:53
From what I know/remember, we have never tried to do it and never discussed it, so I'm +1 here.

But I think we should not do the following mutation:

```diff
- if ($this->someMethodCall() === true) {
+ if (!($this->someMethodCall() === true)) {
}
``` 

because it's a duplicate of 

```diff
- if ($this->someMethodCall() === true) {
+ if ($this->someMethodCall() !== true) {
}
``` 
At the same time, let's look into more complex example and intersections with existing mutators:

Original code: `! (a() || b())`

Boolean matrix:

| a   |      b      |  result |
|----------|:-------------:|------:|
| true |  true | false |
| true |    false   |   false |
| false| true |    false |
| false| false |    true |

**Example 1:** New proposed mutation :

```diff
- ! (a() || b()) 
+ a() || b()
```

The boolean matrix of mutated code is completely different - nice:

| a   |      b      |  result |
|----------|:-------------:|------:|
| true |  true | true |
| true |    false   |   true |
| false| true |    true |
| false| false |    false |

And let's compare to the existing `LogicalOr` mutator:

```diff
- ! (a() || b()) 
+ ! (a() && b()) 
```

The boolean matrix is not duplicated, which is a good thing:

| a   |      b      |  result |
|----------|:-------------:|------:|
| true |  true | false |
| true |    false   |   true |
| false| true |    true |
| false| false |    true |

At this point, introducing the new proposed mutator gives us the new boolean matrix which is a great addition.

Now, let's try to mutate farther, inside the sub-conditions:

**Example 2:** negate `a()` call

```diff
- ! (a() || b()) 
+ ! (!a() || b()) 
```

| a   |      b      |  result |
|----------|:-------------:|------:|
| true |  true | false |
| true |    false   |   true |
| false| true |    false |
| false| false |    false |

The new boolean matrix is not duplicated - great (it means such mutation gives us new cases to be killed).

**Example 3:** negate `b()` call

```diff
- ! (a() || b()) 
+ ! (a() || !b()) 
```

| a   |      b      |  result |
|----------|:-------------:|------:|
| true |  true | false |
| true |    false   |   false |
| false| true |    true |
| false| false |    false |

Again - the new matrix is not duplicated with anything before - good.

Finally, let's try to negate all sub-conditions (this is still not an equivalent by [De Morgan's law](https://en.wikipedia.org/wiki/De_Morgan%27s_laws))

**Example 4:** negate `a()`  and  `b()` call

```diff
- ! (a() || b()) 
+ ! (!a() || !b()) 
```

| a   |      b      |  result |
|----------|:-------------:|------:|
| true |  true | true |
| true |    false   |   false |
| false| true |    false |
| false| false |    false |

We have not duplicated new boolean matrix again - good.

---

That being said, I think the following rules should apply to the new mutator:

- it shoould **not** mutated strict compartisons to `false` and `true` (like `X === true` -> `! (X === true)` because it's a duplicate of `TrueValue` and `FalseValue` mutators
- it should negate expression that contains method calls (Example 1)
- it should negate every method call sub-expression (Example 2 - 3)
- it may (for us to decide) negate all sub-expressions at the same time ((Example 4)

What do you all think?

**Comment by manhunto** [comment] 2022-11-19 11:53
Thank you @maks-rafalko, it is a great analysis! What to do with some complex code that contains elseif? Should condition in elseif be mutate in the same way you described above or should it be omitted?

I was thinking about this mutation you have given in examples 2,3,4 and what to do when there is more than two conditions? For example there is three or more conditions.
Should it be mutated also in every possible way? Like this, example for three condtiions
1. Negate first condition only.
2. Negate second condition only.
3. Negate third condition only.
4. Negate first and second.
5. Negate first and third.
6. Negate second and third.
7. Negate first, second and third. (Like in example 4)
So there is 7 mutations do three conditions. In similar way with four and more conditions.

This mutator should only mutates method calls Or should this mutation also mutate variables or function calls etc.?

What do you think?

**Comment by manhunto** [comment] 2022-11-19 12:09
Another idea come to my mind. What to do if expression is already negated? Should I remove this negation or add another (doubled) negation?

**Comment by maks-rafalko** [comment] 2022-11-19 22:18
> Should condition in elseif be mutate in the same way you described above or should it be omitted?

I think so, yes

> what to do when there is more than two expressions? 

For N expressions we will have always N+2 mutations (negation of the whole expressions, for each of N sub-expressions and for all together). Be it 2 or 5 - doesn't matter.

> This mutator should only mutates method calls Or should this mutation also mutate variables or function calls etc.?

Agree, it should be `$a`, `a()`, `$this->a()` and `self::a()`

> What to do if expression is already negated? Should we remove this negation or add another (doubled) negation?

To make it more understandable for developer, let's remove negation rather than adding doubled negation.

**Comment by manhunto** [comment] 2022-11-20 15:18
I'm implementing it, and I've encountered some interesting case.

```php
$var = a() && b();

if ($var) {
}
```

It would be nice to mutate this line `$var = a() && b();` in the same way as described above for if statement. A similar case is when a method/function returns a boolean value with complex condition (with and/or).

```php
function fooBar() {
return a() && b();
}
```

If we want to have negation for complex boolean expressions, maybe we should consider mutating just `Node\Expr\BinaryOp\BooleanAnd` and `Node\Expr\BinaryOp\BooleaOr` but it looks like hard to implement to avoid duplicated mutations for case when we have 3 and more expressions. For one and two expressions, it is easy to avoid duplications.

**Comment by manhunto** [comment] 2022-11-21 18:34
I prepared POC on my fork branch https://github.com/infection/infection/compare/master...manhunto:infection:feature/negation-in-if-and-boolean

I will be glad if you can glance at it, and assure me that I'm on a good path ;) 
Additionally, I can prepare some e2e tests to protect those mutations from doubling themselves with `LogicalNot`, `FalseValue`, `TureValue` and so on.
I can prepare separate PRs for every mutator if it is easier to check it, but some of them are connected with others, so I want to be sure that you agree with this approach.

I will be away from my computer for a couple of days and will answer all questions and thoughts a bit later.

**Comment by sanmai** [comment] 2022-11-22 03:22
Thanks for all your work. It could be better to open a PR so we can start with reviews.

**Comment by manhunto** [comment] 2022-11-27 00:32
> Thanks for all your work. It could be better to open a PR so we can start with reviews.

I've prepared a PR https://github.com/infection/infection/pull/1753 ;)

**Closed** 2023-05-12 20:15 UTC
Labels: Mutator
